# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration Test

on: [push]

jobs:
  CI_Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python setup.py develop
        pip install -r test_requirements.txt
        pip install .
    - name: Style Check
      run: pep8 coursera_autograder tests
    - name: Unit Tests Except list_graders_tests
      run: |
        nosetests tests/commands/config_tests.py
        nosetests tests/commands/get_resource_limits_tests.py
        nosetests tests/commands/get_status_tests.py
        nosetests tests/commands/grade_tests.py
        nosetests tests/commands/oauth2_tests.py
        nosetests tests/commands/update_resource_limits_tests.py
        nosetests tests/commands/upload_tests.py
    - name: list_graders_tests not found
      run: nosetests tests/commands/list_graders_tests.py:test_list_graders_error_not_found
    - name: list_graders_tests general
      run: nosetests tests/commands/list_graders_tests.py:test_list_graders_error_general
    - name: list_graders_tests ok
      run: nosetests tests/commands/list_graders_tests.py:test_list_graders_ok





